# Generated by Django 3.2.4 on 2021-10-03 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deptno',
            fields=[
                ('deptno', models.IntegerField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=30)),
                ('loc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('empno', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('ename', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('manager', models.CharField(blank=True, max_length=50, null=True)),
                ('hiredate', models.DateField()),
                ('sal', models.IntegerField()),
                ('cmm', models.IntegerField(blank=True, null=True)),
                ('deptno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.deptno')),
            ],
        ),
    ]
