# Generated by Django 3.2.4 on 2021-10-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_remove_emp_hiredate'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='hiredate',
            field=models.DateField(null=True),
        ),
    ]
