# Generated by Django 3.2.4 on 2021-10-04 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_emp_hiredate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp1',
            fields=[
                ('empno', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('ename', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('manager', models.CharField(blank=True, max_length=50, null=True)),
                ('hiredate', models.DateField(null=True)),
                ('sal', models.IntegerField()),
                ('cmm', models.IntegerField(blank=True, null=True)),
                ('deptno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.deptno')),
            ],
        ),
    ]
